dist: trusty
sudo: true

matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin RID=osx-x64 RUN_TESTS=yes CROSS=no CREATE_DEB=no
    - os: linux
      env: TARGET=x86_64-linux-gnu RID=linux-x64 RUN_TESTS=yes CROSS=no CREATE_DEB=yes

language: c

env:
  global:
  - LIBPLIST_VERSION=2.0.1-157
  - LIBUSBMUXD_VERSION=1.1.0-87
  - CFLAGS=-fPIC
  - LIBIMOBILEDEVICE_VERSION=1.2.1-146

before_install:
- test -n $CC && unset CC

install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip2 install --user azure-cli; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip install requests urllib3 pyOpenSSL --force --upgrade; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install --user azure-cli; fi


before_script:
- wget https://qmcdn.blob.core.windows.net/imobiledevice/libplist-$RID-$LIBPLIST_VERSION.tar.gz
- wget https://qmcdn.blob.core.windows.net/imobiledevice/libusbmuxd-$RID-$LIBUSBMUXD_VERSION.tar.gz
- wget https://qmcdn.blob.core.windows.net/imobiledevice/libimobiledevice-$RID-$LIBIMOBILEDEVICE_VERSION.tar.gz
- mkdir $HOME/ext
- tar -xvzf libplist-$RID-$LIBPLIST_VERSION.tar.gz -C $HOME/ext
- tar -xvzf libusbmuxd-$RID-$LIBUSBMUXD_VERSION.tar.gz -C $HOME/ext
- tar -xvzf libimobiledevice-$RID-$LIBIMOBILEDEVICE_VERSION.tar.gz -C $HOME/ext
- find $HOME/ext
- LC_CTYPE=C LANG=C find $HOME/ext/lib/pkgconfig/ -name '*.pc' -print0 | xargs -0 sed -i -e 's@/travis/out@/travis/ext@g'
- LC_CTYPE=C LANG=C find $HOME/ext/lib/ -name '*.la' -print0 | xargs -0 sed -i -e 's@/travis/out@/travis/ext@g'

script:
- export CFLAGS="$CFLAGS -I$HOME/ext/include"
- export PKG_CONFIG_PATH=$HOME/ext/lib/pkgconfig:$PKG_CONFIG_PATH
- export LDFLAGS="$LDFLAGS -L$HOME/ext/lib"
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CFLAGS="$CFLAGS -I/usr/local/opt/openssl/include"; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl/lib"; fi
- pkg-config --print-errors --variable=prefix libplist
- pkg-config --print-errors --variable=prefix libusbmuxd
- pkg-config --print-errors --variable=prefix libimobiledevice-1.0
- ./autogen.sh --prefix=$HOME/out --host=$TARGET --without-cython --enable-static=no --enable-shared=yes
- make

after_success:
- make install
- tar -zcvf libideviceactivation-$RID.tar.gz -C $HOME/out .
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then az=$HOME/Library/Python/2.7/bin/az; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then az=$HOME/.local/bin/az; fi
- $az storage blob upload --verbose --file libideviceactivation-$RID.tar.gz --container-name imobiledevice --name libideviceactivation-$RID-1.0.0-$TRAVIS_BUILD_NUMBER.tar.gz

after_failure:
- cat config.log
